server:
  port: 8080 # 서버가 실행될 포트 번호

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:  # 카카오 로그인 설정
            client-id: c305c20845d7d5bf52199d9566b1e52c # 환경변수로 설정 (보안상 중요!)
            client-secret: 7V7cBRONLFB1Or1Ij5hyYt6W7S3jA5Rr
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: https://spacefarm.shop/login/oauth2/code/kakao
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:  # 카카오 OAuth2 제공자 설정
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  # 카카오에서 사용자 식별자로 사용할 속성

## JWT 토큰 설정
jwt:
  header: Authorization
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM
  accessTokenValidityInSeconds: 3600 # 1시간
  refreshTokenValidityInSeconds: 604800 # 7일

## 로그 레벨 설정
logging:
  level:
    org.springframework.security: DEBUG  # 스프링 시큐리티 디버그 로그
    com.example.oauth: DEBUG  # 우리 패키지 디버그 로그
